CREATE TABLE "blogs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(255) NOT NULL,
	"summary" text NOT NULL,
	"content" text NOT NULL,
	"published_at" timestamp NOT NULL,
	"source_name" varchar(100) NOT NULL,
	"source_url" varchar(500) NOT NULL,
	"tags" jsonb NOT NULL,
	"region" jsonb NOT NULL,
	"companies" jsonb,
	"sector" varchar(100) NOT NULL,
	"financial_impact" text,
	"key_numbers" jsonb,
	"image_url" varchar(500),
	"image_source" varchar(100),
	"image_attribution" varchar(255),
	"image_license" varchar(100),
	"image_alt_text" varchar(255),
	"ai_generated_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
